spring:
  application:
    name: house

  datasource:
    name: mydb
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1994
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.onion.pojo